# Generated by Django 4.1.5 on 2023-05-07 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profileusr_notis'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileusr',
            name='socialUser',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
